### ISSUE TITLE
[XMAN] Minimum Clean Speed

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#11]
### Environment

- Demo
- Operational

### Expected behaviour
SPVR needs a MCS tool which will force all Mach advisory to MCS instead of XMAN Advisory
No other XMAN choices can be proposed in MCS mode but information should be shared with other sector as normal XMAN behavior

**Comment by kouak** [comment]
### Proposal
A switch on the supervisor HMI to activate/deactivate MCS mode
When MCS mode is activated, remove all mach buttons and put a "MCS" one in place.

What kind of UI should we produce on the supervisor HMI ? We need to consider the case of multiple destinations (e.g LSZH in MCS mode, EGLL in normal mode).

**Comment by OneATC** [comment]
This one is easy … we need a MCS EGLL and a MCS LSZH (2 buttons).

 

De : Benjamin Beret [mailto:notifications@github.com] 
Envoyé : mardi 3 mai 2016 21:48
À : devteamreims/4ME
Objet : Re: [devteamreims/4ME] [XMAN] Minimum Clean Speed (#11)

 


Proposal


A switch on the supervisor HMI to activate/deactivate MCS mode
When MCS mode is activated, remove all mach buttons and put a "MCS" one in place.

What kind of UI should we produce on the supervisor HMI ? We need to consider the case of multiple destinations (e.g LSZH in MCS mode, EGLL in normal mode).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub <https://github.com/devteamreims/4ME/issues/11#issuecomment-216644324>   <https://github.com/notifications/beacon/ALSp93jXVcz2NCcLC4-9YUPTZd5KITjQks5p96aAgaJpZM4INfAm.gif> 



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.xman.orchestrator/commit/a6e15b30565a63d277a6f5d9378dbe770c36ddc2
https://github.com/devteamreims/4me.xman.orchestrator/commit/547b75e98629b5455bb4fffdb02f9dc05beba6d7
https://github.com/devteamreims/4me.xman.orchestrator/commit/04cddd12e40108ac8b2f4fb79110800e41505c28

https://github.com/devteamreims/4me.react/commit/cd71ce0d0955cd7194f0e340b5ef90422adf9ac3
https://github.com/devteamreims/4me.react/commit/161f4cd428bd27d30692bb931d687287ff26798f

TODO :
- [ ] When MCS mode is enabled, remove speed buttons, display "MCS" button only.

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.react/commit/a488d89e69f07c44ee59b96627ea0cac69a91a16
https://github.com/devteamreims/4me.react/commit/de69221eb2f88888df1c2c3cee2d023be0bd7168
https://github.com/devteamreims/4me.react/commit/5c10b1640aa31d7af7b34704fb96ece0c33e2fbd

https://github.com/devteamreims/4me.xman.orchestrator/commit/aee428f9a347c6ae11282daaf674ec2d621e242e
https://github.com/devteamreims/4me.xman.orchestrator/commit/23fd98f57c27cbdb5788c8b31f576fcb729ad4ee
https://github.com/devteamreims/4me.xman.orchestrator/commit/f54664cf1ea46e20a8ec451956d99bf1fe735610
https://github.com/devteamreims/4me.xman.orchestrator/commit/54c090ad2f05950f161a034aef4c00d4ef125f28

Should be done.

**Comment by kouak** [comment]
Reopen :
- [ ] Remove TTO when MCS mode is enabled. Display "MCS MODE" instead.

**Comment by kouak** [comment]
http://i.imgur.com/jOk9Ocs.png

https://github.com/devteamreims/4me.react/commit/4aac19b8f36d80c5d8eb0039bceaf6eea0a099a7
