### ISSUE TITLE
XMAN OFF

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#26]
### XMAN OFF Status

SPVR can decide to turn XMAN Off in case of CB situation or overload situation. 
SPVR should have a button to turn XMAN off.

On CWP no more XMAN advisory should be displayed

**Comment by kouak** [comment]
Related to #11.

Should the "XMAN OFF" switch be global ? Sector based (disable XMAN in URME, let it be in URMN) or destination based (disable XMAN for EGLL, maintain status for LSZH ?). Or both ?

**Comment by OneATC** [comment]
This one is more tricky … I would recommend to change the logic from the current behavior (a big red flashing XMAN Off alarm) and go for a XMAN OFF EGLL and XMAN OFF LSZH buttons with a “silent” effect on the CWP : no alarm, the info is just not distributed anymore. To be discussed …

 

De : Benjamin Beret [mailto:notifications@github.com] 
Envoyé : mardi 3 mai 2016 21:50
À : devteamreims/4ME
Objet : Re: [devteamreims/4ME] XMAN OFF (#26)

 

Related to #11 <https://github.com/devteamreims/4ME/issues/11> .

Should the "XMAN OFF" switch be global ? Sector based (disable XMAN in URME, let it be in URMN) or destination based (disable XMAN for EGLL, maintain status for LSZH ?). Or both ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub <https://github.com/devteamreims/4ME/issues/26#issuecomment-216644678>   <https://github.com/notifications/beacon/ALSp9wDaTx5YWQtaUSTu2KN_9NnUbUKLks5p96bWgaJpZM4IWRRz.gif> 



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by Rubbens** [comment]
Let's clarify the requirements 
XMAN Off is an XMAN status, the SPVR can decide regarding the OPS situation to block the advisory on the CWP and make XMAN silent on an CWP point of view.
It is different from XMAN crash where currently we have a big red alarm flashing.

But we also have to define alarms on CWP and CDS and next in the SPVR HMI when an XMAN connection has been lost or an XMAN service (orchestrator) has crashed. But these alarm are different from XMAN Off requirements.

**Comment by kouak** [comment]
Should we just display an empty list on CWPs in case of XMAN OFF ?

I think this could lead to confusion amongst controllers ("Why is the list empty even though I have EGLL inbounds in my airspace ?").

My suggestion is to display some kind of message on the CWPs like "XMAN for EGLL has been deactivated by the supervisor".

When the situation settles down, controllers could then provide feedback to the supervisor who could have forgotten to reenable XMAN.

**Comment by OneATC** [comment]
The current situation when the XMAN OFF button has been activated is : The IHM continues to deliver flight list and advisories and on top of that we have a large red  XMAN OFF banner.

 

I believe we should try to keep the HMI as simpler as possible for the CWP and also avoiding massive polluting indication that may disturb the attention from the radar.

 

So the idea would be to keep the flight list yes and to just stop pushing the advisories. What we may add is a “XMAN OFF” indication in the TTO column replacing the time value (so that the CWP understand that it’s not a tech issue).

 

De : Benjamin Beret [mailto:notifications@github.com] 
Envoyé : vendredi 6 mai 2016 00:03
À : devteamreims/4ME
Cc : OneATC; Comment
Objet : Re: [devteamreims/4ME] XMAN OFF (#26)

 

Should we just display an empty list on CWPs in case of XMAN OFF ?

I think this could lead to confusion amongst controllers ("Why is the list empty even though I have EGLL inbounds in my airspace ?").

My suggestion is to display some kind of message on the CWPs like "XMAN for EGLL has been deactivated by the supervisor".

When the situation settles down, controllers could then provide feedback to the supervisor who could have forgotten to reenable XMAN.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub <https://github.com/devteamreims/4ME/issues/26#issuecomment-217292828> Image supprimée par l'expéditeur.



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by Rubbens** [comment]
I fully agree let's keep the list and just kill the advisory and if we can
we should bring this info XMAN off on the cwp by notification

In order to avoid to stay on this XMAN off status I would propose on the
CdS HMI to propose to the CdS to run XMAN off for a special period of time :
15' 30' 45' 60' then the XMAN will turn on again with a notification to CdS
and cwp


-- 
Thomas Leparlier

Le 6 mai 2016 à 08:31:41, OneATC (notifications@github.com) a écrit:

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.xman.orchestrator/commit/a6e15b30565a63d277a6f5d9378dbe770c36ddc2
https://github.com/devteamreims/4me.xman.orchestrator/commit/547b75e98629b5455bb4fffdb02f9dc05beba6d7
https://github.com/devteamreims/4me.xman.orchestrator/commit/04cddd12e40108ac8b2f4fb79110800e41505c28

https://github.com/devteamreims/4me.react/commit/cd71ce0d0955cd7194f0e340b5ef90422adf9ac3
https://github.com/devteamreims/4me.react/commit/161f4cd428bd27d30692bb931d687287ff26798f

TODO :
- [ ] Hide flight list on CWPs with bound sectors when XMAN is OFF

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.react/commit/a488d89e69f07c44ee59b96627ea0cac69a91a16
https://github.com/devteamreims/4me.react/commit/de69221eb2f88888df1c2c3cee2d023be0bd7168

https://github.com/devteamreims/4me.xman.orchestrator/commit/aee428f9a347c6ae11282daaf674ec2d621e242e
https://github.com/devteamreims/4me.xman.orchestrator/commit/23fd98f57c27cbdb5788c8b31f576fcb729ad4ee
https://github.com/devteamreims/4me.xman.orchestrator/commit/f54664cf1ea46e20a8ec451956d99bf1fe735610

This should do it.

**Comment by kouak** [comment]
TODO :
- [ ] Remove TTO when XMAN is OFF (replace with 'OFF')

**Comment by kouak** [comment]
http://i.imgur.com/TYnafRo.png

https://github.com/devteamreims/4me.react/commit/4aac19b8f36d80c5d8eb0039bceaf6eea0a099a7
