### ISSUE TITLE
[ARCID] Make FL colors more coherent in point profile

### ISSUE THREAD

**Issue by kouak** [devteamreims/4ME#3]
### Environment
- ~~Demo~~
- Operational

Use LFEE layers and set a color per layer.

FLs below 120 should not be colored.

**Comment by Rubbens** [comment]
No need to have a display regarding Reims UAC layers make it generic

**Comment by kouak** [comment]
After the first wave of demo usage, I didn't get any negative feedback regarding these colors.

Using LFEE layers may let users miss a FL change (e.g 320 to 340).

After discussion with @Rubbens it seems current solution is best.

@OneATC: What's your input on this ?

**Comment by OneATC** [comment]
Ok let’s keep it like that … It’s only temporary anyway, waiting for a graph display.

 

De : Benjamin Beret [mailto:notifications@github.com] 
Envoyé : mardi 3 mai 2016 21:39
À : devteamreims/4ME
Cc : OneATC; Mention
Objet : Re: [devteamreims/4ME] [ARCID] Make FL colors more coherent in point profile (#3)

 

After the first wave of demo usage, I didn't get any negative feedback regarding these colors.

Using LFEE layers may let users miss a FL change (e.g 320 to 340).

After discussion with @Rubbens <https://github.com/Rubbens>  it seems current solution is best.

@OneATC <https://github.com/OneATC> : What's your input on this ?

—
You are receiving this because you were mentioned.
Reply to this email directly or  <https://github.com/devteamreims/4ME/issues/3#issuecomment-216641890> view it on GitHub  <https://github.com/notifications/beacon/ALSp98J6WwqMNdNpIptQdeli6asQjW6lks5p96RJgaJpZM4IIWJZ.gif> 



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by kouak** [comment]
Closing this particular issue.
