### ISSUE TITLE
FL filtering on mouse over

### ISSUE THREAD

**Issue by OneATC** [devteamreims/4ME#39]
### Environment
- Demo
- Operational

### Actual behaviour :
It's filtering on the absolute value e.g. when a flight is 357 instead of 360, it's filtering on 357 and you won't see any 360 ...

### Expected behaviour : 
it should be filtering on a level band e.g. from 355 to 364, the flight should be considered at 360.

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.react/commit/ac66815f830332381befd501d66245c2b2f98843

I just implemented a simple solution based off distance between hovered FL and flight FL.

If flight FL is within 500 feet of hovered FL, then the flight won't be toned down.

Hovering FL360 will tone down anything outside the [355, 365] range. Hovering FL357 will tone down anything outside [352, 362] range.

Please reopen if this behaviour doesn't meet the expected behaviour.
