### ISSUE TITLE
Time and Date

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#51]
Please add the time and date on 4Me-Core

**Comment by kouak** [comment]
http://i.imgur.com/FkLuMbZ.png

That's a quick version.

Posititionning stuff in the center of the blue bar is quite tricky with the library I use and will require a few more work hours.

If this result is acceptable for now, I suggest we leave it here until after the summer. If not, then I suppose we can ship the first version without the clock, because I won't have time to do a much better job before the deadline.

**Comment by Rubbens** [comment]
Perfect
I don't consider as mandatory to set time center on the top of the HMI
I called the top left corner the "information corner" it makes complete
sense to add time to this corner
For the summer milestone This is green light for the next I am not sure we
shall center it

Is it possible to add date also?


-- 
Thomas Leparlier

Le 15 mai 2016 à 14:25:22, Benjamin Beret (notifications@github.com) a
écrit:

**Comment by OneATC** [comment]
Let's keep it like that ...
Le 15 mai 2016 2:25 PM, "Benjamin Beret" <notifications@github.com> a
écrit :

**Comment by kouak** [comment]
With date proposals :
http://i.imgur.com/QFaHePs.png
http://i.imgur.com/kbAEo7n.png
http://i.imgur.com/pLgbc9x.png

**Comment by OneATC** [comment]
Vote for third one :-)
Le 15 mai 2016 2:56 PM, "Benjamin Beret" <notifications@github.com> a
écrit :

**Comment by Rubbens** [comment]
I do prefer the second one but I don’t really care third one is also very good.
Let’s the boss decide ;)



Le 15 mai 2016 à 14:58:37, OneATC (notifications@github.com) a écrit:

Vote for third one :-)
Le 15 mai 2016 2:56 PM, "Benjamin Beret" <notifications@github.com> a
écrit :

**Comment by OneATC** [comment]
Whatever .. let's ask a girl ... Elsa !
Le 15 mai 2016 3:06 PM, "Rubbens" <notifications@github.com> a écrit :

I do prefer the second one but I don’t really care third one is also very
good.
Let’s the boss decide ;)




Le 15 mai 2016 à 14:58:37, OneATC (notifications@github.com) a écrit:

Vote for third one :-)
Le 15 mai 2016 2:56 PM, "Benjamin Beret" <notifications@github.com> a
écrit :

> With date proposals :
> http://i.imgur.com/QFaHePs.png
> http://i.imgur.com/kbAEo7n.png
> http://i.imgur.com/pLgbc9x.png
>
> —
> You are receiving this because you commented.

> Reply to this email directly or view it on GitHub
> <https://github.com/devteamreims/4ME/issues/51#issuecomment-219284309>
>
—
You are receiving this because you authored the thread.

Reply to this email directly or view it on GitHub

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/devteamreims/4ME/issues/51#issuecomment-219284764>

**Comment by Rubbens** [comment]
Can we condor the issues closed?

**Comment by kouak** [comment]
Closing for now, pending feedback from users.
