### ISSUE TITLE
NIL/-1 delay handling

### ISSUE THREAD

**Issue by kouak** [devteamreims/4ME#62]
For some reason, we can sometimes find rows like this : `<asdd:sequencingPoint delay="NIL" type="COP" smoothedDelay="NIL">` in the XMAN XML.

How should we handle this ?
On the UI side, we should display "0" as delay but what should we do on the backend side ? Raise an error ? Treat it like a 0 delay ?

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.react/commit/4117e89fcbc5fc2d2e7cf2c7c9c78f583fe548f0

**Comment by Rubbens** [comment]
This is an AMAN misbehavior 
The UI should display 0.
On the backend side we should at least log this error and treat it as a 0 delay.

Statistic about the error will be welcome.

**Comment by kouak** [comment]
Advisory is in the ops log output now. This should be easy to catch.

**Comment by OneATC** [comment]
You can also find

 

·         <asdd:sequencingPoint delay="NIL" type="COP" smoothedDelay="PT0H3M0S">

·         <asdd:sequencingPoint delay="PT0H3M0S" type="COP" smoothedDelay="NIL">

·         <asdd:sequencingPoint delay="NIL" type="COP" smoothedDelay="NIL">

 

I’m not sure it’s an error perhaps, it’s due to a lack or absence of data. If there’s not enough occurrences to calculated a smoothed delay or if the aircraft has already passed the COP.

 

By the way, are you using smoothed delay to calculate the Mach reduction or the delay ?

 

De : Rubbens [mailto:notifications@github.com] 
Envoyé : jeudi 19 mai 2016 17:53
À : devteamreims/4ME
Objet : Re: [devteamreims/4ME] NIL/-1 delay handling (#62)

 

This is an AMAN misbehavior 
The UI should display 0.
On the backend side we should at least log this error and treat it as a 0 delay.

Statistic about the error will be welcome.

**Comment by kouak** [comment]
We're using delay.

The capture process (i.e only letting a mach reduction grow) looks like a smoothing mechanism to me.

For reference, the smoothed delay is logged alongside the reims delay when an advisory updates.
