### ISSUE TITLE
XMAN List Instability

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#80]
### Actual behavior
Instable list : The list stays as expected during couple if sec the disappear without any alarm on the Service status bar.

### Expected behavior
XMAN List should not be erased at any time

**Comment by kouak** [comment]
Related to #77

**Comment by kouak** [comment]
June 7th log :

There seems to be some kind of failure here : https://gist.github.com/kouak/ac48c5517db5d9cc58cb3bb6b85f6e83#file-xman-fail-log

At 12:56:22, everythings looks fine, clients are notified about multiple flights.

5 seconds later, after a position refresh cycle, clients are told to display an empty XMAN list.

In each flight log, we can see the position changing to an empty object (lat = 0, long = 0). This situation keeps on for ~20minutes until 13:15, where the flight position is updated to relevant data. At this point, clients are notified with a proper flight list.

It looks like the issue lies with the flight position data chain. I don't have logs for this part yet.

**Comment by OneATC** [comment]
That makes sense regarding the difference with the demo ... Is ADS-B more
reliable than Elvira ? 😂

We discussed that already, perhaps it's worth protecting the Xman service
from radar data loss only using time references in that case.
Le 12 juin 2016 1:09 PM, "Benjamin Beret" <notifications@github.com> a
écrit :

**Comment by kouak** [comment]
Bug has been identified and is not 4me related, closing.
