### ISSUE TITLE
ETFMS Profile: "Nothing Found" for a valid aircraft"

### ISSUE THREAD

**Issue by ClemGLAD** [devteamreims/4ME#87]
![img_20160613_230011](https://cloud.githubusercontent.com/assets/18627265/16054742/c2aff1ea-326e-11e6-9abd-e841c67587a4.jpg)
![img_20160613_230050](https://cloud.githubusercontent.com/assets/18627265/16054748/c4796272-326e-11e6-9218-a2a890389f09.jpg)
![img_20160613_230057](https://cloud.githubusercontent.com/assets/18627265/16054749/c5d72d02-326e-11e6-9196-45b796041215.jpg)
Unable to find LXG22A via ETFMS Profile. Valid ACT strip on monday 13/06.

**Comment by Rubbens** [comment]
This is normal 

If Auto completion does not give you the flight plan please type the full ARCID and click on search 

You should be able to find your ETFMS profile
Activé 14 juin 2016 à 20:32:12, ClemGLAD (notifications@github.com) a écrit:




Unable to find LXG22A via ETFMS Profile. Valid ACT strip.

**Comment by kouak** [comment]
Technically, this is not normal behavior : the flight is in LFEE airspace, the flight should appear in LFERMS traffic volume and thus the flight should be listed in autocomplete.

I don't have access to ETFMS archives on the NOP portal on this day. I won't investigate further for now, we'll see if this happens again when time boundaries are tweaked in #84

**Comment by sylvainmondou** [comment]
Actually, this flight has been excluded from LFERMS traffic volume, because it has been captured by the flow EDY>EDU (from Maatricht to Rhein airspace). It probably has been on direct route, and entered some airspaces of Maastricht and Rhein after entering LFEEHE. 
Although this is a very peculiar case, a way to avoid this would be to send the request not on traffic volume LFERMS, but on airspace LFEERMS. The later is not filtered at all.

**Comment by kouak** [comment]
This should be an easy fix. Thanks for your input @sylvainmondou.

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.b2b.flightPlanFetcher/commit/b67a8e44ee2af75782ff69f2686a7cf42fc81c0a
